### ISSUE TITLE
Erro ao abrir o certificado pfx

### ISSUE THREAD

**Issue by willmartinsmg** [willmdrs/pdf-signer-brazil#2]
Olá!

Quando executo o meu código, ele exibe um erro informando que não foi possível abrir o certificado no formato pfx.

O certificado está na mesma pasta do código e está com as permissão de leitura, escrita e gravação para todos e mesmo assim está dando esse erro.

```
[Nest] 18474   - 11/06/2021 14:49:08   [ExceptionsHandler] ENOENT: no such file or directory, open 'certificado.pfx' +1922ms
Error: ENOENT: no such file or directory, open 'certificado.pfx'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at GeneralService.listSector (/Users/william/Sites/nestjs_cd/dist/general/general.service.js:26:30)
    at GeneralController.listSector (/Users/william/Sites/nestjs_cd/dist/general/general.controller.js:25:36)
    at /Users/william/Sites/nestjs_cd/node_modules/@nestjs/core/router/router-execution-context.js:38:29
```

Alguém sabe como corrigir esse erro?

**Comment by willmartinsmg** [comment]
Eu precisava apontar o caminho certo e por isso estava gerando o erro acima.
